// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cghwwiuhuhheqefhurmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnaHd3aXVodWhoZXFlZmh1cm10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjkzMjksImV4cCI6MjA2OTMwNTMyOX0.jLkyArX3Zq7jOFek2DIuzVR0V3nk8bSIf1teEJ53OGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});